# Generated by Django 5.0.6 on 2024-07-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alter_jobseeker_job_seeker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='job_seeker_id',
            field=models.CharField(default='jnE0krimml', max_length=10, unique=True),
        ),
    ]
