# Generated by Django 5.0.6 on 2024-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiter_id',
            field=models.CharField(default='r9tw5POV9Z', max_length=10, unique=True),
        ),
    ]
