# Generated by Django 5.0.6 on 2024-07-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_recruiter_recruiter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiter_id',
            field=models.CharField(default='rgOEf7CgNw', max_length=10, unique=True),
        ),
    ]
