# Generated by Django 5.0.6 on 2024-07-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_recruiter_recruiter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiter_id',
            field=models.CharField(default='rmuSfbY6sy', max_length=10, unique=True),
        ),
    ]
