# Generated by Django 5.0.6 on 2024-07-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_alter_recruiter_recruiter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiter_id',
            field=models.CharField(default='rnSdxQc6r1', max_length=10, unique=True),
        ),
    ]
